debug = false
insecure-entitlements = ["security.insecure"]
[worker.oci]
  gc = true
  gckeepstorage = "90%"
  max-parallelism = 8
  cniPoolSize = 16

  [[worker.oci.gcpolicy]]
    all = true
    keepBytes = "100GB"
    keepDuration = "48h"
    # filters = [ "type==source.local", "type==exec.cachemount", "type==source.git.checkout"]

[worker.containerd]
  address = "/run/containerd/containerd.sock"
  enabled = true
  platforms = [ "linux/amd64" ]
  namespace = "buildkit"
  gc = true
  # gckeepstorage sets storage limit for default gc profile, in bytes.
  gckeepstorage = "90%"
  # maintain a pool of reusable CNI network namespaces to amortize the overhead
  # of allocating and releasing the namespaces
  cniPoolSize = 16

  # configure the containerd runtime
  [worker.containerd.runtime]
    name = "io.containerd.runc.v2"
    options = { BinaryName = "runc" }

  [[worker.containerd.gcpolicy]]
    all = true
    keepBytes = "100GB"
    keepDuration = 172800
    # filters = [ "type==source.local", "type==exec.cachemount", "type==source.git.checkout"]

[registry."host.docker.internal:5000"]
  http = true
  insecure = true