#!/bin/sh

### BEGIN INIT INFO
# Provides:          consul
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start Consul agent in dev mode
# Description:       Starts Consul agent in dev mode.
### END INIT INFO

case "$1" in 
    start)
        echo "Starting Consul..."
        /usr/bin/consul agent -dev > /var/log/consul.log 2>&1 &
        ;;
    stop)
        echo "Stopping Consul..."
        pkill consul
        ;;
    *)
        echo "Usage: /etc/init.d/consul {start|stop}"
        exit 1
        ;;
esac

exit 0
