#!/bin/sh

### BEGIN INIT INFO
# Provides:          nomad
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start Nomad agent in dev mode
# Description:       Starts Nomad agent in dev mode.
### END INIT INFO

case "$1" in 
    start)
        echo "Starting Nomad..."
        /usr/bin/nomad agent -dev -config=/workspace/nomad/config > /var/log/nomad.log 2>&1 &
        ;;
    stop)
        echo "Stopping Nomad..."
        pkill nomad
        ;;
    *)
        echo "Usage: /etc/init.d/nomad {start|stop}"
        exit 1
        ;;
esac

exit 0
